service: blockies-generator

plugins:
  - "@silvermine/serverless-plugin-cloudfront-lambda-edge"
  - serverless-plugin-include-dependencies
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1

functions:
  blockiesGenerator:
    name: 'blockies-generator'
    handler: index.handler
    memorySize: 128
    timeout: 2
    lambdaAtEdge:
      distribution: 'BlockiesDistribtuion'
      eventType: 'origin-request'

resources:
  Resources:
    BlockiesDistribtuion:
      Type: 'AWS::CloudFront::Distribution'
      Properties:
        DistributionConfig:
          Aliases:
            - ${env:BLOCKIES_DOMAIN}
          DefaultCacheBehavior:
            TargetOriginId: 'DummyOrigin'
            ViewerProtocolPolicy: 'redirect-to-https'
            DefaultTTL: 31536000 # one year, default MaxTTL
            Compress: true
            ForwardedValues:
              QueryString: true
              QueryStringCacheKeys:
                - size
              Cookies:
                Forward: 'none'
          Enabled: true
          PriceClass: 'PriceClass_200'
          HttpVersion: 'http2'
          ViewerCertificate:
            AcmCertificateArn: ${env:ACM_CERTIFICATE_ARN}
            SslSupportMethod: 'sni-only'
            MinimumProtocolVersion: 'TLSv1.1_2016'
          Origins:
            - Id: 'DummyOrigin'
              DomainName: 'shipchain.io'  # Needs to be a valid domain, but no requests will actually be sent to the origin
              CustomOriginConfig:
                OriginProtocolPolicy: https-only